" plugin
runtime ./plugin/install.vim
runtime ./plugin/setting.vim
" vim-setting
runtime ./vim-setting/main.vim
runtime ./vim-setting/color.vim
runtime ./vim-setting/autocmd.vim
runtime ./vim-setting/command.vim
" aliasmap
runtime ./map/inore.vim
runtime ./map/nnore.vim
runtime ./map/vnore.vim
