" plugin
runtime ./plugin/install.vim
runtime ./plugin/setting.vim
" vim-setting
runtime ./vim-setting/main.vim
runtime ./vim-setting/color.vim
" aliasmap
runtime ./noremap/inore.vim
runtime ./noremap/nnore.vim
runtime ./noremap/vnore.vim
