" plugin
runtime init/plugin/install.vim
runtime init/plugin/setting.vim
" vim-setting
runtime init/vim-setting/main.vim
runtime init/vim-setting/color.vim
" aliasmap
runtime init/noremap/inore.vim
runtime init/noremap/nnore.vim
runtime init/noremap/vnore.vim
