image: Visual Studio 2017

configuration: Default

platform:
  - x64
  - Win32

before_build:
  - cmd: |
          git clone --depth 1 https://chromium.googlesource.com/external/gyp
          gyp\gyp rcedit.gyp --depth .

build:
  project: rcedit.sln
  parallel: true
  verbosity: minimal

after_build:
  - cmd: if %PLATFORM%==Win32 (move Default\rcedit.exe Default\rcedit-x86.exe)
  - cmd: if %PLATFORM%==x64 (move Default\rcedit.exe Default\rcedit-x64.exe)

branches:
  only:
    - master

artifacts:
  - path: Default\*.exe

deploy:
  - provider: GitHub
    release: Rcedit $(APPVEYOR_REPO_TAG_NAME)
    tag: $(APPVEYOR_REPO_TAG_NAME)
    description: '(placeholder)'
    auth_token:
      secure: lVaYho+MDDKAQH4aImQub/L5ORlENgZ4utufxWAetovWnIsWiwFCkgFRIcIRMWz5
    artifact: /.*\.exe/
    draft: true
    force_update: true
    prerelease: false
    on:
      appveyor_repo_tag: true
