vim.api.nvim_set_keymap("n", "<Space>v", ":call sml#mode_on()<CR>", { noremap = true, silent = true })
vim.api.nvim_set_keymap("n", "<C-t>", ":call DeolFloat()<CR>", { noremap = true, silent = true })
vim.api.nvim_set_keymap("n", "<C-s>", ":Ag<CR>", { noremap = true, silent = true })
vim.api.nvim_set_keymap("n", "<C-q>", ":Lspsaga hover_doc<CR>", { noremap = true, silent = true })
vim.api.nvim_set_keymap("n", "<C-j>", ":Lspsaga diagnostic_jump_next<CR>", { noremap = true, silent = true })
vim.api.nvim_set_keymap("n", "<C-f>", ":lua vim.lsp.buf.format()<CR>", { noremap = true, silent = true })
vim.api.nvim_set_keymap("n", "<C-h>", "<C-w>h<CR>", { noremap = true, silent = true })
vim.api.nvim_set_keymap("n", "<C-j>", "<C-j>j<CR>", { noremap = true, silent = true })
vim.api.nvim_set_keymap("n", "<C-k>", "<C-w>k<CR>", { noremap = true, silent = true })
vim.api.nvim_set_keymap("n", "<C-l>", "<C-w>l<CR>", { noremap = true, silent = true })
vim.api.nvim_set_keymap("n", "gd", ":Lspsaga lsp_finder<CR>", { noremap = true, silent = true })
vim.api.nvim_set_keymap("n", "gp", ":Lspsaga preview_definition<CR>", { noremap = true, silent = true })
vim.api.nvim_set_keymap("n", "gr", ":Lspsaga rename<CR>", { noremap = true, silent = true })
vim.api.nvim_set_keymap("n", "fp", ":Prettier<CR>", { noremap = true, silent = true })
-- Fern mapping
vim.api.nvim_set_keymap("n", "<C-n>", ":FernToggle<CR>", { noremap = true, silent = true })
-- Git Gutter mapping
vim.api.nvim_set_keymap("n", "g[", ":GitGutterPrevHunk<CR>", { noremap = true, silent = true })
vim.api.nvim_set_keymap("n", "g]", ":GitGutterNextHunk<CR>", { noremap = true, silent = true })
vim.api.nvim_set_keymap("n", "gh", ":GitGutterLineHighlightsToggle<CR>", { noremap = true, silent = true })
