customCommands:
- key: 'c'
  prompts:
    - type: 'input'
      title: 'Commit message'
      initialValue: ''
  command: "pummit '{{index .PromptResponses 0}}'"
  context: 'files'
  description: 'commit changes(Custom Command)'
- key: "C"
  command: 'git reset --soft HEAD^'
  context: 'files'
  description: 'Undo latest commit'
gui:
  language: 'ja'
