lastupdatecheck: 0
recentrepos:
- /home/hidemaru/dotfiles
- /home/hidemaru/Code/MyHomePage/VirtualSlime-API
- /home/hidemaru/Code/MyHomePage
- /tmp/VirtualSlime
- /tmp/VirtualSlime/VirtualSlime-API
- /home/hidemaru/Code/Tweepic
- /home/hidemaru/Code/join-form
- /home/hidemaru/sshconf
startuppopupversion: 5
customcommandshistory: []
hidecommandlog: false
ignorewhitespaceindiffview: false
