lastupdatecheck: 0
recentrepos:
- /home/hidemaru/dotfiles
- /home/hidemaru/Code/pummit
- /home/hidemaru/temp
- /home/hidemaru/Code/sandbox
- /home/hidemaru/Code/nuts
startuppopupversion: 5
customcommandshistory: []
hidecommandlog: false
