lastupdatecheck: 0
recentrepos:
- /home/hidemaru/dotfiles
- /home/hidemaru/Code/Awesome-Repository
startuppopupversion: 5
customcommandshistory: []
hidecommandlog: false
ignorewhitespaceindiffview: false
