lastupdatecheck: 0
recentrepos:
- /home/hidemaru/dotfiles
- /home/hidemaru/Code/VirtualSlime
- /home/hidemaru/Code/VirtualSlime-API
- /home/hidemaru/Code/Tweepic
- /home/hidemaru/Code/join-form
- /home/hidemaru/sshconf
startuppopupversion: 5
customcommandshistory: []
hidecommandlog: false
ignorewhitespaceindiffview: false
