lastupdatecheck: 0
recentrepos:
- /home/hidemaru/dotfiles
- /home/hidemaru/Code/pummit
- /home/hidemaru/Code/testrepo
- /home/hidemaru/Code/thinkerAI-Installer
- /home/hidemaru/Code/thinkerAI
- /home/hidemaru/Code/Awesome-HelloWorld
- /home/hidemaru/Code/sandbox
- /home/hidemaru/Code/MyHomePage
- /home/hidemaru/Code/nuts
- /home/hidemaru/temp
startuppopupversion: 5
customcommandshistory: []
hidecommandlog: false
