name: build
on: push
jobs:
  compile:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-10.15, macos-11, ubuntu-18.04, ubuntu-20.04]
        mode: [debug, release]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules : recursive
    - uses: actboy168/setup-luamake@master
    - run: luamake -mode ${{ matrix.mode }}
    - if: matrix.os == 'macos-11'
      run: luamake -universal -mode ${{ matrix.mode }}
    - if: runner.os == 'Linux'
      run: luamake lua test/glibc-version.lua
